title: Hijab Maida Official
description: Pengiriman dari Bandung 
cover-img: /path/to/bg.jpg

author:
  type      : # "person" (default), "organization"
  name      : Your Name
  url       :
  avatar    : # path or url of avatar image (square)
  bio       : I am an amazing person.
  email     :
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name

theme: jekyll-theme-cayman
